"""
product_knowledge.py

What the platform does and how a user does it.

WHY THIS EXISTS, AND WHY IT IS NOT THE SOURCE CODE
--------------------------------------------------
The instinct is that an agent needs the repositories to answer "how do I do
this in Vome". It does not, and reaching for code would make the answers
worse.

Source code says what the system computes. A user-education answer has to say
what the person clicks. Reading `opportunity_app/views.py` tells you an
endpoint exists and a queryset is filtered. It does not tell you "Database
page, filter by opportunity, Select All, Export", which is the actual answer.
Worse, an agent reasoning from code produces answers phrased in endpoints,
models and field names, which is exactly the internal detail that must never
reach a customer.

The knowledge for educating users already exists, in four places, none of
which is git:

  1. Help centre articles, synced nightly into Postgres with language-aware
     full text search. Written for users, step by step. The best source, and
     it needs a database connection.
  2. The in-app Setup Guide, in knowledge_book/setup_guide_source.md. Seven
     stages of procedural, plain-language instruction. On disk, no database
     needed. This module reads it.
  3. The feature catalog, in knowledge_book/feature_catalog.json. Module-level
     description of what the platform does. Good for "does this exist at all",
     weak on steps. Also on disk.
  3b. The product's own UI strings, via product_strings.py. Authoritative on
     whether a feature exists and what it is called, because the codebase
     forbids literal UI text so every visible label is in the translation
     files. Silent on the order of operations.
  4. The knowledge book in `knowledge_sections`, generated by the weekly pass
     over thousands of closed tickets. This is the prior-learnings layer, and
     it needs a database connection.

This module covers 2 and 3, so that an agent has real product knowledge even
with no database reachable. It is a floor, not a ceiling: with Postgres
connected, the help centre is better and should be preferred.

WHERE CODE ACCESS DOES BELONG
-----------------------------
Diagnosis, not education. Whether a reported behaviour is a real defect, what
shipped just before a regression started, and which module owns a symptom.
All of that feeds internal notes and engineer handoffs. See
`vomeos/integrations/code_search.py`.
"""

from __future__ import annotations

import json
import re
from functools import lru_cache
from pathlib import Path

BOOK = Path(__file__).parent / "knowledge_book"
SETUP_GUIDE = BOOK / "setup_guide_source.md"
FEATURE_CATALOG = BOOK / "feature_catalog.json"

_STOPWORDS = frozenset(
    """
    a an and are as at be by can cannot could do does for from get has have
    how in into is it its me my not of on or our so that the their them then
    there these this to up us was we what when where which who why will with
    you your would able want need please thanks hi hello issue problem help
    """.split()
)


def _tokens(text: str) -> set[str]:
    words = re.findall(r"[a-z][a-z0-9-]{2,}", (text or "").lower())
    return {w for w in words if w not in _STOPWORDS}


@lru_cache(maxsize=1)
def _setup_sections() -> list[tuple[str, str]]:
    """The Setup Guide split into (heading, body) at its ### boundaries."""
    if not SETUP_GUIDE.exists():
        return []
    text = SETUP_GUIDE.read_text(encoding="utf-8")
    sections: list[tuple[str, str]] = []
    heading = ""
    buffer: list[str] = []
    for line in text.splitlines():
        if line.startswith("### "):
            if heading and buffer:
                sections.append((heading, "\n".join(buffer).strip()))
            heading = line[4:].strip()
            buffer = []
        elif line.startswith("## "):
            # A stage heading. Keep it as context on the next section.
            if heading and buffer:
                sections.append((heading, "\n".join(buffer).strip()))
            heading, buffer = "", []
        else:
            buffer.append(line)
    if heading and buffer:
        sections.append((heading, "\n".join(buffer).strip()))
    return sections


@lru_cache(maxsize=1)
def _catalog_entries() -> list[tuple[str, str]]:
    """The feature catalog flattened into (label, text)."""
    if not FEATURE_CATALOG.exists():
        return []
    try:
        data = json.loads(FEATURE_CATALOG.read_text(encoding="utf-8"))
    except ValueError:
        return []
    entries: list[tuple[str, str]] = []

    def walk(node, label: str) -> None:
        if isinstance(node, dict):
            for key, value in node.items():
                walk(value, f"{label} {key}".strip())
        elif isinstance(node, list):
            for item in node:
                walk(item, label)
        elif isinstance(node, str) and len(node) > 40:
            entries.append((label, node))

    walk(data, "")
    return entries


def _rank(query: str, pool: list[tuple[str, str]], limit: int,
          threshold: float) -> list[tuple[float, str, str]]:
    """Rank sections against a question.

    Plain coverage of the query's words does not work here. The Setup Guide
    has sections thousands of words long, and a long enough section contains
    every common word, so "volunteer cannot see shifts" scored a perfect
    match against "What your plan covers". Two corrections:

      * the heading carries most of the weight, because a section about
        exporting says so in its title;
      * body coverage is damped by length, so a long section has to match
        more of the question to beat a short, on-topic one.
    """
    wanted = _tokens(query)
    if not wanted:
        return []

    scored = []
    for heading, body in pool:
        head_tokens = _tokens(heading)
        body_tokens = _tokens(body)
        if not head_tokens and not body_tokens:
            continue

        head_hit = len(wanted & head_tokens) / len(wanted)
        body_hit = len(wanted & body_tokens) / len(wanted)

        # Longer sections are likelier to contain any given word by accident.
        # 200 tokens is roughly a focused section; beyond that the body
        # signal is discounted toward nothing.
        length_penalty = 200 / (200 + max(len(body_tokens) - 200, 0))

        score = (0.7 * head_hit) + (0.3 * body_hit * length_penalty)
        if score >= threshold:
            scored.append((score, heading, body))

    scored.sort(key=lambda row: row[0], reverse=True)
    return scored[:limit]


def search_product_knowledge(
    query: str, limit: int = 3, threshold: float = 0.25
) -> list[dict]:
    """Setup Guide sections, then catalog entries, best match first."""
    hits = [
        {"source": "Setup Guide", "title": h, "body": b, "score": round(s, 3)}
        for s, h, b in _rank(query, _setup_sections(), limit, threshold)
    ]
    if len(hits) < limit:
        hits += [
            {"source": "Feature catalog", "title": h, "body": b,
             "score": round(s, 3)}
            for s, h, b in _rank(
                query, _catalog_entries(), limit - len(hits), threshold
            )
        ]
    return hits


def describe_knowledge(query: str, limit: int = 3, chars: int = 700) -> str:
    """The `kb_matches` context block, as prose for an agent.

    Prefers the help centre when a database is reachable, because those
    articles are the published answer a customer can also be pointed at.
    Falls back to the on-disk Setup Guide and catalog so an agent is never
    left with no product knowledge at all.
    """
    blocks: list[str] = []

    try:
        from database import search_kb_articles_db

        articles = search_kb_articles_db(query, limit=limit) or []
        for article in articles:
            body = (article.get("body") or "")[:chars]
            blocks.append(
                f"Help centre article '{article.get('title')}': {body}"
            )
    except Exception:
        blocks.append(
            "Help centre search did NOT run (no database reachable). "
            "Coverage there is UNKNOWN."
        )

    for hit in search_product_knowledge(query, limit=limit):
        blocks.append(
            f"{hit['source']} section '{hit['title']}': {hit['body'][:chars]}"
        )

    # The product's own UI strings. Authoritative on whether a feature exists
    # and what it is called, silent on the steps to reach it.
    try:
        from product_strings import describe_strings

        blocks.append(describe_strings(query))
    except Exception as exc:
        blocks.append(f"UI string search unavailable ({exc}).")

    # Where in the product this lives, derived from the frontend routes and
    # component tree. Gives the page to name in an answer.
    try:
        from product_navigation import describe_navigation

        blocks.append(describe_navigation(query))
    except Exception as exc:
        blocks.append(f"Navigation search unavailable ({exc}).")

    if len(blocks) == 1 and blocks[0].startswith("Help centre search did NOT"):
        blocks.append(
            "No Setup Guide or feature catalog section matched either."
        )
    elif not blocks:
        return "No matching product knowledge found (searches ran cleanly)."
    return "\n\n".join(blocks)
